name: daroulmoukhtycomputer
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Defines the version and build number for the application.
version: 1.0.0+1

# Specifies the Dart SDK version.
environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Additional dependencies
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  http: ^1.2.2

# Development dependencies for testing and linting.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  shared_preferences: ^2.0.15

# Flutter-specific configuration.
flutter:
  # Ensures Material Icons font is included with the application.
  uses-material-design: true

  # Specifies the assets to include in the application.
  assets:
    - images/p1.jpg
    - images/p2.jpg
    - images/p3.jpg
    - images/logo.jpg

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
